### PR TITLE
s/master/main for phase{1,2}

### PR DESCRIPTION
**Pull request by aparcar**
This is just a collection where things may change

### CODE REVIEW

**Comment by f00b4r0** [comment]
missing quite a few references to "master" branch. Try `git grep '\bmaster\b'`. HTH

**Comment by aparcar** [comment]
Thanks @f00b4r0 I added some more.

**Comment by ynezz** [comment]
Update pls.

**Comment by aparcar** [comment]
Rebased, sorry for the delay

**Pull request merged**
